// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_content_delivery_bucket": "gatsby-contentful",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "http://gatsby-contentful.s3-website-ap-southeast-2.amazonaws.com"
};


export default awsmobile;
